spring.application.name=f20

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/f20_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Flyway Config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedrohvidals@gmail.com
spring.mail.password=ruux rmzm hpce eymz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Rqueue Config
rqueue.redis.enabled=true