CREATE TABLE IF NOT EXISTS tb_email_codes (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    email_code VARCHAR(100) NOT NULL,
    is_used BOOLEAN DEFAULT FALSE,
    dtcreate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dtupdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES tb_users(id)
)